classdef SetEMotorRequest < robotics.ros.Message
    %SetEMotorRequest MATLAB implementation of dobot_magician_driver/SetEMotorRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'dobot_magician_driver/SetEMotorRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '1c4f9ff9c9cde962b415c9e227d1cfb7' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Index
        IsEnabled
        Speed
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Index', 'IsEnabled', 'Speed'} % List of non-constant message properties
        ROSPropertyList = {'index', 'is_enabled', 'speed'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SetEMotorRequest(msg)
            %SetEMotorRequest Construct the message object SetEMotorRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function index = get.Index(obj)
            %get.Index Get the value for property Index
            index = int8(obj.JavaMessage.getIndex);
        end
        
        function set.Index(obj, index)
            %set.Index Set the value for property Index
            validateattributes(index, {'numeric'}, {'nonempty', 'scalar'}, 'SetEMotorRequest', 'Index');
            
            obj.JavaMessage.setIndex(index);
        end
        
        function isenabled = get.IsEnabled(obj)
            %get.IsEnabled Get the value for property IsEnabled
            isenabled = logical(obj.JavaMessage.getIsEnabled);
        end
        
        function set.IsEnabled(obj, isenabled)
            %set.IsEnabled Set the value for property IsEnabled
            validateattributes(isenabled, {'logical', 'numeric'}, {'nonempty', 'scalar'}, 'SetEMotorRequest', 'IsEnabled');
            
            obj.JavaMessage.setIsEnabled(isenabled);
        end
        
        function speed = get.Speed(obj)
            %get.Speed Get the value for property Speed
            speed = single(obj.JavaMessage.getSpeed);
        end
        
        function set.Speed(obj, speed)
            %set.Speed Set the value for property Speed
            validateattributes(speed, {'numeric'}, {'nonempty', 'scalar'}, 'SetEMotorRequest', 'Speed');
            
            obj.JavaMessage.setSpeed(speed);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Index = obj.Index;
            cpObj.IsEnabled = obj.IsEnabled;
            cpObj.Speed = obj.Speed;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Index = strObj.Index;
            obj.IsEnabled = strObj.IsEnabled;
            obj.Speed = strObj.Speed;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Index = obj.Index;
            strObj.IsEnabled = obj.IsEnabled;
            strObj.Speed = obj.Speed;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.dobot_magician_driver.SetEMotorRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.dobot_magician_driver.SetEMotorRequest;
            obj.reload(strObj);
        end
    end
end
